name: Update Documentation

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
  workflow_dispatch:

jobs:
  update-docs:
    name: Auto-generate Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Generate README (using LazyDocs itself!)
        run: |
          export GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
          node dist/cli.js generate --type readme --input ./src --output ./README_NEW.md || true
        continue-on-error: true
      
      - name: Check if README changed
        id: check_changes
        run: |
          if [ -f README_NEW.md ]; then
            if ! diff -q README.md README_NEW.md > /dev/null 2>&1; then
              echo "changed=true" >> $GITHUB_OUTPUT
            else
              echo "changed=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs: auto-update README with LazyDocs'
          title: '📚 Auto-update Documentation'
          body: |
            This PR was automatically generated by LazyDocs to update the documentation.
            
            Please review the changes before merging.
          branch: docs/auto-update
          delete-branch: true
